import os
import subprocess
import sys
import json
import shutil
from pathlib import Path

# Thử import tkinter để làm Cửa sổ chọn thư mục GUI
try:
    import tkinter as tk
    from tkinter import filedialog
    HAS_TKINTER = True
except ImportError:
    HAS_TKINTER = False

# ==========================================
# BẢNG MÀU ANSI
# ==========================================
C_RED = '\033[91m'
C_GREEN = '\033[92m'
C_YELLOW = '\033[93m'
C_CYAN = '\033[96m'
C_BLUE = '\033[94m'
C_MAGENTA = '\033[95m'
C_RESET = '\033[0m'
C_BOLD = '\033[1m'
C_DIM = '\033[2m'

# ==========================================
# CẤU HÌNH & LỊCH SỬ (CACHE)
# ==========================================
CONFIG_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config.json")

def load_config():
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, 'r', encoding='utf-8') as f:
                return json.load(f)
        except:
            return {"history": []}
    return {"history": []}

def save_config(target_dir):
    config = load_config()
    history = config.get("history", [])
    
    if target_dir in history:
        history.remove(target_dir)
    history.insert(0, target_dir) # Đưa lên đầu
    
    # Chỉ giữ 5 lịch sử gần nhất
    config["history"] = history[:5]
    
    with open(CONFIG_FILE, 'w', encoding='utf-8') as f:
        json.dump(config, f, indent=4)

# ==========================================
# HÀM TIỆN ÍCH GIT & HỆ THỐNG
# ==========================================
def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

def check_git_installed():
    try:
        subprocess.run(["git", "--version"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
        return True
    except FileNotFoundError:
        return False

def run_git_cmd(cmd_list, cwd, capture_output=False, show_progress=False, check=True):
    """
    show_progress=True sẽ để nguyên stdout/stderr để thấy được thanh tải của Git
    """
    try:
        if capture_output:
            result = subprocess.run(cmd_list, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, check=check)
            return True, result.stdout.strip()
        else:
            print(f"{C_DIM}>> Đang chạy: {' '.join(cmd_list)}{C_RESET}")
            # Nếu cần show progress, không dùng PIPE
            stderr_target = None if show_progress else subprocess.PIPE
            stdout_target = None if show_progress else subprocess.PIPE
            
            subprocess.run(cmd_list, cwd=cwd, stdout=stdout_target, stderr=stderr_target, check=check)
            return True, ""
    except subprocess.CalledProcessError as e:
        err_msg = e.stderr if e.stderr else str(e)
        return False, err_msg

def get_git_info(cwd):
    """Lấy thông tin Branch và Status để vẽ Dashboard"""
    if not os.path.isdir(os.path.join(cwd, ".git")):
        return "Chưa khởi tạo Git", "Không có dữ liệu", "Chưa cấu hình", "Chưa cấu hình"
    
    branch = "Unknown"
    status_summary = "Sạch (Clean)"
    user_name = "Chưa cấu hình"
    user_email = "Chưa cấu hình"
    
    # Lấy branch
    ok, out = run_git_cmd(["git", "branch", "--show-current"], cwd, capture_output=True, check=False)
    if ok and out:
        branch = out
        
    # Lấy status
    ok, out = run_git_cmd(["git", "status", "--porcelain"], cwd, capture_output=True, check=False)
    if ok:
        if out:
            lines = out.split('\n')
            status_summary = f"{len(lines)} file(s) thay đổi"
            
    # Lấy Account
    ok, out = run_git_cmd(["git", "config", "user.name"], cwd, capture_output=True, check=False)
    if ok and out: user_name = out
    ok, out = run_git_cmd(["git", "config", "user.email"], cwd, capture_output=True, check=False)
    if ok and out: user_email = out
            
    return branch, status_summary, user_name, user_email

def auto_generate_gitignore(cwd):
    """Tự động quét và tạo .gitignore nếu chưa có"""
    gitignore_path = os.path.join(cwd, ".gitignore")
    if os.path.exists(gitignore_path):
        return
        
    ignores = []
    if os.path.exists(os.path.join(cwd, "package.json")):
        ignores.extend(["node_modules/", "npm-debug.log", ".env"])
    has_python = any(f.endswith('.py') for f in os.listdir(cwd) if os.path.isfile(os.path.join(cwd, f)))
    if has_python:
        ignores.extend(["__pycache__/", "*.pyc", ".venv/", "venv/", ".env"])
        
    ignores.extend([".DS_Store", "Thumbs.db"])
    
    if ignores:
        with open(gitignore_path, 'w', encoding='utf-8') as f:
            f.write("# Auto-generated by Git Easy Toolkit\n")
            f.write("\n".join(ignores) + "\n")
        print(f"{C_GREEN}✨ Tự động tạo file .gitignore cho dự án!{C_RESET}")

def pause():
    input(f"\n{C_YELLOW}Nhấn Enter để tiếp tục...{C_RESET}")

# ==========================================
# CÁC MENU CON (SUB-MENUS) DỰA TRÊN TÀI LIỆU
# ==========================================

def menu_setup(target_dir):
    while True:
        clear_screen()
        print(f"{C_CYAN}{C_BOLD}=== 1. KHỞI ĐẦU & CẤU HÌNH (SETUP) ==={C_RESET}")
        print(" 1. Init   : Biến thư mục hiện tại thành Git repo")
        print(" 2. Clone  : Tải dự án từ GitHub/GitLab về máy")
        print(" 3. Remote : Kết nối code máy với server trực tuyến")
        print(" 4. Config : Cài đặt Tên và Email cá nhân (Global/Local)")
        print(f" {C_RED}0. Quay lại{C_RESET}")
        
        choice = input(f">> Chọn: ").strip()
        if choice == '1':
            run_git_cmd(["git", "init"], target_dir, show_progress=True)
            pause()
        elif choice == '2':
            url = input(">> Nhập URL Github/GitLab: ").strip()
            if url: run_git_cmd(["git", "clone", "--progress", url, "."], target_dir, show_progress=True)
            pause()
        elif choice == '3':
            url = input(">> Nhập URL Origin mới: ").strip()
            if url: run_git_cmd(["git", "remote", "add", "origin", url], target_dir, show_progress=True)
            pause()
        elif choice == '4':
            name = input(">> Tên hiển thị (User Name): ").strip()
            email = input(">> Email (User Email): ").strip()
            is_global = input(">> Lưu Global (áp dụng cho toàn máy) hay Local (chỉ mục này)? (g/L): ").strip().lower()
            scope = "--global" if is_global == 'g' else "--local"
            if name: run_git_cmd(["git", "config", scope, "user.name", f'"{name}"'], target_dir)
            if email: run_git_cmd(["git", "config", scope, "user.email", f'"{email}"'], target_dir)
            print(f"{C_GREEN}✅ Đã cập nhật thông tin!{C_RESET}")
            pause()
        elif choice == '0':
            break

def menu_daily_flow(target_dir):
    while True:
        clear_screen()
        print(f"{C_CYAN}{C_BOLD}=== 2. QUY TRÌNH HÀNG NGÀY (DAILY FLOW) ==={C_RESET}")
        print(" 1. Pull   : Cập nhật code mới nhất từ team")
        print(" 2. Status : Xem mình đã sửa những file nào")
        print(" 3. Push   : Đẩy code (Bao gồm Add + Commit + Push tự động)")
        print(f" {C_RED}0. Quay lại{C_RESET}")
        
        choice = input(f">> Chọn: ").strip()
        if choice == '1':
            branch = get_git_info(target_dir)[0]
            ok, err = run_git_cmd(["git", "pull", "origin", branch], target_dir, show_progress=True)
            if not ok and ("conflict" in str(err).lower() or "merge" in str(err).lower()):
                print(f"\n{C_RED}🔥 XUNG ĐỘT (CONFLICT) 🔥{C_RESET}")
                ans = input(">> Xóa thay đổi của bạn lấy trên mạng? (y/N): ").strip().lower()
                if ans == 'y':
                    run_git_cmd(["git", "reset", "--hard", f"origin/{branch}"], target_dir)
                else:
                    run_git_cmd(["git", "merge", "--abort"], target_dir)
            pause()
        elif choice == '2':
            run_git_cmd(["git", "status"], target_dir, show_progress=True)
            pause()
        elif choice == '3':
            auto_generate_gitignore(target_dir)
            status = get_git_info(target_dir)[1]
            if status == "Sạch (Clean)":
                print(f"{C_YELLOW}⚠️ Không có thay đổi nào mới để Push!{C_RESET}")
            else:
                msg = input(">> Nhập lời nhắn (Commit Message): ").strip()
                if not msg: msg = "Cập nhật code tự động"
                branch = get_git_info(target_dir)[0]
                run_git_cmd(["git", "add", "."], target_dir)
                run_git_cmd(["git", "commit", "-m", msg], target_dir)
                run_git_cmd(["git", "push", "--progress", "origin", branch], target_dir, show_progress=True)
            pause()
        elif choice == '0':
            break

def menu_branching(target_dir):
    while True:
        clear_screen()
        print(f"{C_CYAN}{C_BOLD}=== 3. QUẢN LÝ NHÁNH (BRANCHING) ==={C_RESET}")
        print(" 1. Branch       : Liệt kê các nhánh đang có")
        print(" 2. Checkout -b  : Tạo nhánh mới và nhảy sang đó")
        print(" 3. Checkout     : Chuyển đổi qua lại giữa các nhánh")
        print(" 4. Merge        : Gộp code từ nhánh khác vào nhánh hiện tại")
        print(" 5. Branch -d    : Xóa nhánh (Dưới máy)")
        print(" 6. Branch -m    : Đổi tên nhánh hiện tại")
        print(" 7. Push Delete  : Xóa nhánh trên Server (Github/Gitlab)")
        print(f" {C_RED}0. Quay lại{C_RESET}")
        
        choice = input(f">> Chọn: ").strip()
        if choice == '1':
            run_git_cmd(["git", "branch", "-a"], target_dir, show_progress=True)
            pause()
        elif choice == '2':
            bname = input(">> Tên nhánh mới: ").strip()
            if bname: run_git_cmd(["git", "checkout", "-b", bname], target_dir, show_progress=True)
            pause()
        elif choice == '3':
            bname = input(">> Tên nhánh muốn chuyển tới: ").strip()
            if bname: run_git_cmd(["git", "checkout", bname], target_dir, show_progress=True)
            pause()
        elif choice == '4':
            bname = input(">> Tên nhánh muốn gộp VÀO nhánh hiện tại: ").strip()
            if bname: run_git_cmd(["git", "merge", bname], target_dir, show_progress=True)
            pause()
        elif choice == '5':
            bname = input(">> Tên nhánh muốn xóa (local): ").strip()
            if bname: run_git_cmd(["git", "branch", "-d", bname], target_dir, show_progress=True)
            pause()
        elif choice == '6':
            bname = input(">> Nhập tên mới cho nhánh hiện tại: ").strip()
            if bname: run_git_cmd(["git", "branch", "-m", bname], target_dir, show_progress=True)
            pause()
        elif choice == '7':
            bname = input(">> Tên nhánh muốn xóa trên Server: ").strip()
            if bname: run_git_cmd(["git", "push", "origin", "--delete", bname], target_dir, show_progress=True)
            pause()
        elif choice == '0':
            break

def menu_inspection(target_dir):
    while True:
        clear_screen()
        print(f"{C_CYAN}{C_BOLD}=== 4. KIỂM TRA & SO SÁNH (INSPECTION) ==={C_RESET}")
        print(" 1. Log   : Xem lịch sử commit (Sơ đồ)")
        print(" 2. Diff  : Xem chi tiết từng dòng code thay đổi (chưa commit)")
        print(" 3. Show  : Xem nội dung của 1 commit cụ thể")
        print(" 4. Blame : Xem ai sửa từng dòng trong file")
        print(f" {C_RED}0. Quay lại{C_RESET}")
        
        choice = input(f">> Chọn: ").strip()
        if choice == '1':
            run_git_cmd(["git", "log", "--oneline", "--graph", "--all", "-n", "20"], target_dir, show_progress=True)
            pause()
        elif choice == '2':
            run_git_cmd(["git", "diff"], target_dir, show_progress=True)
            pause()
        elif choice == '3':
            c_id = input(">> Nhập mã Commit (VD: a1b2c3d): ").strip()
            if c_id: run_git_cmd(["git", "show", c_id], target_dir, show_progress=True)
            pause()
        elif choice == '4':
            file_path = input(">> Nhập đường dẫn file (VD: main.py): ").strip()
            if file_path: run_git_cmd(["git", "blame", file_path], target_dir, show_progress=True)
            pause()
        elif choice == '0':
            break

def menu_undoing(target_dir):
    while True:
        clear_screen()
        print(f"{C_CYAN}{C_BOLD}=== 5. SỬA LỖI & HOÀN TÁC (UNDOING) ==={C_RESET}")
        print(" 1. Restore/Clean  : Hủy thay đổi chưa commit (Khôi phục file)")
        print(" 2. Stash          : Tạm cất code đang làm dở")
        print(" 3. Stash Pop      : Lấy lại code đã cất")
        print(" 4. Commit --amend : Sửa lại nội dung/message commit gần nhất")
        print(" 5. Reset --soft   : Hủy commit gần nhất (Giữ lại code)")
        print(" 6. Reset --hard   : Hủy commit (XÓA SẠCH CODE MỚI)")
        print(" 7. Revert         : Tạo commit mới để đảo ngược thay đổi cũ")
        print(f" {C_RED}0. Quay lại{C_RESET}")
        
        choice = input(f">> Chọn: ").strip()
        if choice == '1':
            ans = input(">> CẢNH BÁO: Mất toàn bộ code chưa lưu. Tiếp tục? (y/N): ").strip().lower()
            if ans == 'y':
                run_git_cmd(["git", "restore", "."], target_dir)
                run_git_cmd(["git", "clean", "-fd"], target_dir)
                print(f"{C_GREEN}Đã khôi phục thành công!{C_RESET}")
            pause()
        elif choice == '2':
            msg = input(">> Lời nhắn cất giữ (Tùy chọn): ").strip()
            if msg: run_git_cmd(["git", "stash", "save", f'"{msg}"'], target_dir, show_progress=True)
            else: run_git_cmd(["git", "stash"], target_dir, show_progress=True)
            pause()
        elif choice == '3':
            run_git_cmd(["git", "stash", "pop"], target_dir, show_progress=True)
            pause()
        elif choice == '4':
            msg = input(">> Nhập Message mới (Để trống nếu chỉ muốn gộp file): ").strip()
            if msg: run_git_cmd(["git", "commit", "--amend", "-m", msg], target_dir, show_progress=True)
            else: run_git_cmd(["git", "commit", "--amend", "--no-edit"], target_dir, show_progress=True)
            pause()
        elif choice == '5':
            run_git_cmd(["git", "reset", "--soft", "HEAD~1"], target_dir, show_progress=True)
            pause()
        elif choice == '6':
            c_id = input(">> Nhập mã Commit muốn quay về (Bỏ trống = HEAD): ").strip()
            c_id = c_id if c_id else "HEAD"
            ans = input(f">> CẢNH BÁO: Mọi code sau {c_id} sẽ BỊ XÓA VĨNH VIỄN. Tiếp tục? (y/N): ").strip().lower()
            if ans == 'y': run_git_cmd(["git", "reset", "--hard", c_id], target_dir, show_progress=True)
            pause()
        elif choice == '7':
            c_id = input(">> Nhập mã Commit cần đảo ngược: ").strip()
            if c_id: run_git_cmd(["git", "revert", c_id], target_dir, show_progress=True)
            pause()
        elif choice == '0':
            break

def menu_advanced(target_dir):
    while True:
        clear_screen()
        print(f"{C_CYAN}{C_BOLD}=== 6. NÂNG CAO (ADVANCED) ==={C_RESET}")
        print(" 1. Tag          : Đánh dấu phiên bản phát hành (VD: v1.0)")
        print(" 2. Cherry-pick  : Trích xuất 1 commit từ nhánh khác đắp vào nhánh này")
        print(f" {C_RED}0. Quay lại{C_RESET}")
        
        choice = input(f">> Chọn: ").strip()
        if choice == '1':
            tname = input(">> Tên Tag (VD: v1.0): ").strip()
            msg = input(">> Mô tả Tag: ").strip()
            if tname: run_git_cmd(["git", "tag", "-a", tname, "-m", msg], target_dir, show_progress=True)
            pause()
        elif choice == '2':
            c_id = input(">> Mã Commit muốn trích (Cherry-pick): ").strip()
            if c_id: run_git_cmd(["git", "cherry-pick", c_id], target_dir, show_progress=True)
            pause()
        elif choice == '0':
            break


# ==========================================
# GIAO DIỆN DASHBOARD CHÍNH (TUI)
# ==========================================
def draw_dashboard(target_dir):
    clear_screen()
    branch, status, user_name, user_email = get_git_info(target_dir)
    
    print(f"{C_CYAN}{C_BOLD}╔════════════════════════════════════════════════════════════════════╗{C_RESET}")
    print(f"{C_CYAN}{C_BOLD}║              🚀 GIT EASY TOOLKIT PRO (DASHBOARD)                   ║{C_RESET}")
    print(f"{C_CYAN}{C_BOLD}╠════════════════════════════════════════════════════════════════════╣{C_RESET}")
    
    # Kẻ khung thông tin
    dir_display = target_dir if len(target_dir) <= 50 else target_dir[:47] + "..."
    account_display = f"{user_name} ({user_email})"
    account_display = account_display if len(account_display) <= 50 else account_display[:47] + "..."
    
    print(f"{C_CYAN}║ {C_YELLOW}📁 Thư mục: {C_RESET}{dir_display:<53} {C_CYAN}║{C_RESET}")
    print(f"{C_CYAN}║ {C_MAGENTA}🌿 Nhánh:   {C_RESET}{branch:<53} {C_CYAN}║{C_RESET}")
    print(f"{C_CYAN}║ {C_GREEN}📊 Status:  {C_RESET}{status:<53} {C_CYAN}║{C_RESET}")
    print(f"{C_CYAN}║ {C_BLUE}👤 Account: {C_RESET}{account_display:<53} {C_CYAN}║{C_RESET}")
    
    print(f"{C_CYAN}{C_BOLD}╠════════════════════════════════════════════════════════════════════╣{C_RESET}")
    print(f"{C_CYAN}{C_BOLD}║                          [ DANH MỤC LỆNH ]                         ║{C_RESET}")
    print(f"{C_CYAN}║ {C_RESET} 1. ⚙️ Khởi tạo & Cấu hình      4. 🔍 Lịch sử & Kiểm tra          {C_CYAN}║{C_RESET}")
    print(f"{C_CYAN}║ {C_RESET} 2. 🔄 Quy trình làm việc       5. ↩️ Sửa lỗi & Hoàn tác          {C_CYAN}║{C_RESET}")
    print(f"{C_CYAN}║ {C_RESET} 3. 🌿 Quản lý nhánh            6. 🚀 Nâng cao                    {C_CYAN}║{C_RESET}")
    print(f"{C_CYAN}║                                                                    ║{C_RESET}")
    print(f"{C_CYAN}║ {C_YELLOW} 7. 📁 Đổi thư mục làm việc                                       {C_CYAN}║{C_RESET}")
    print(f"{C_CYAN}║ {C_RED} 0. ❌ Thoát                                                      {C_CYAN}║{C_RESET}")
    print(f"{C_CYAN}{C_BOLD}╚════════════════════════════════════════════════════════════════════╝{C_RESET}")

def browse_folder_gui():
    if not HAS_TKINTER:
        return None
    root = tk.Tk()
    root.withdraw() # Ẩn cửa sổ chính
    root.attributes('-topmost', True) # Hiện lên trên cùng
    folder_path = filedialog.askdirectory(title="Chọn thư mục làm việc Git")
    root.destroy()
    return folder_path

def ask_directory():
    config = load_config()
    history = config.get("history", [])
    
    while True:
        clear_screen()
        print(f"{C_CYAN}{C_BOLD}=== CHỌN THƯ MỤC LÀM VIỆC ==={C_RESET}")
        
        print(f"\n{C_YELLOW}💡 Gợi ý: Kéo thả thư mục vào màn hình đen này, hoặc chọn từ Menu dưới đây:{C_RESET}")
        if HAS_TKINTER:
            print(f"\n  {C_BOLD}[0] 📂 Mở cửa sổ chọn thư mục (Duyệt bằng chuột){C_RESET}")
            
        if history:
            print(f"\n{C_YELLOW}🕒 Lịch sử gần đây:{C_RESET}")
            for idx, path in enumerate(history):
                print(f"  [{idx + 1}] {path}")
            print(f"\n>> Gõ {C_GREEN}[Số]{C_RESET} để chọn, hoặc {C_GREEN}Kéo Thả{C_RESET} thư mục mới vào đây:")
        else:
            print(f"\n>> Nhập đường dẫn thư mục:")
            
        raw_path = input(f">> {C_RESET}").strip()
        
        # Nếu chọn Mở Cửa Sổ GUI
        if raw_path == '0' and HAS_TKINTER:
            print(f"{C_DIM}Đang mở cửa sổ chọn thư mục...{C_RESET}")
            selected_dir = browse_folder_gui()
            if selected_dir and os.path.isdir(selected_dir):
                save_config(selected_dir)
                return selected_dir
            else:
                print(f"{C_RED}❌ Đã hủy chọn thư mục.{C_RESET}")
                input("Nhấn Enter để thử lại...")
                continue
                
        # Nếu nhập số từ lịch sử
        if raw_path.isdigit() and 1 <= int(raw_path) <= len(history):
            target = history[int(raw_path) - 1]
            if os.path.isdir(target):
                save_config(target)
                return target
            else:
                print(f"{C_RED}❌ Thư mục này không còn tồn tại trên máy!{C_RESET}")
                history.remove(target) # Xóa khỏi lịch sử ảo
                # Lưu lại config để loại bỏ thư mục hỏng
                config["history"] = history
                with open(CONFIG_FILE, 'w', encoding='utf-8') as f:
                    json.dump(config, f, indent=4)
                input("Nhấn Enter...")
                continue
                
        target_dir = raw_path.strip('"').strip("'")
        target_dir = os.path.expanduser(target_dir)

        if os.path.isdir(target_dir):
            save_config(target_dir)
            return target_dir
        else:
            print(f"{C_RED}❌ Thư mục không tồn tại. Vui lòng thử lại!{C_RESET}")
            input("Nhấn Enter để tiếp tục...")


def main():
    if not check_git_installed():
        print(f"{C_RED}❌ LỖI: Máy tính của bạn chưa cài đặt Git!{C_RESET}")
        input("Nhấn Enter để thoát...")
        sys.exit()

    # Hỗ trợ nhận đường dẫn trực tiếp từ tham số dòng lệnh
    target_dir = ""
    if len(sys.argv) > 1 and os.path.isdir(sys.argv[1]):
        target_dir = sys.argv[1]
        save_config(target_dir)
    else:
        target_dir = ask_directory()
    
    while True:
        draw_dashboard(target_dir)
        choice = input(f"{C_BOLD}>> Nhập danh mục (0-7): {C_RESET}").strip()

        if choice == '1':
            menu_setup(target_dir)
        elif choice == '2':
            menu_daily_flow(target_dir)
        elif choice == '3':
            menu_branching(target_dir)
        elif choice == '4':
            menu_inspection(target_dir)
        elif choice == '5':
            menu_undoing(target_dir)
        elif choice == '6':
            menu_advanced(target_dir)
        elif choice == '7':
            target_dir = ask_directory()
        elif choice == '0':
            clear_screen()
            print(f"\n{C_CYAN}🚀 Tạm biệt! Chúc bạn code vui vẻ!{C_RESET}\n")
            break

if __name__ == "__main__":
    if os.name == 'nt': os.system('color')
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n\n{C_RED}Đã thoát chương trình!{C_RESET}")
        sys.exit()
